# NUMPY-ASSIGNMENT

In [ ]:
 Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.
## SOLUTION:

## yes data type of list_ and array both different because list_ variable contain list data and array variable contain numpy data and it create array of the list.

In [1]:
import numpy as np

In [8]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [9]:
type(list_)

list

In [12]:
array_list = np.array(object = list_)

In [17]:
type(array_list)

numpy.ndarray

In [20]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [21]:
list_ = [ '1' , '2' , '3' , '4' , '5' ]

In [22]:
array_list = np.array(object = list_)

In [25]:
print("Data type of each element in list_")
for element in list_:
    print(type(element))

Data type of each element in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [26]:
print("Data type of each element in array_list")
for element in array_list:
    print(type(element))

Data type of each element in array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:

## array_list = np.array(object = list_, dtype = int)

In [27]:
array_list = np.array(object = list_, dtype=int)

In [28]:
array_list

array([1, 2, 3, 4, 5])

## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [29]:
list_

['1', '2', '3', '4', '5']

In [30]:
array_list

array([1, 2, 3, 4, 5])

## yes in list_ data type are string format and array_list contain the integer data 

In [31]:
print("Data type of each element in list_")
for element in list_:
    print(type(element))

Data type of each element in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [32]:
print("Now Data type of each element in array_list")
for element in array_list:
    print(type(element))

Now Data type of each element in array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:

## (i)	 shape

## (ii) size
## SOLUTION:

In [33]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [34]:
num_array = np.array(object = num_list)

In [35]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
num_array.shape

(2, 3)

In [38]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function

In [39]:
zeroes_array = np.zeros((3,3))

In [40]:
zeroes_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [41]:
identity_matrix = np.identity((5,5))

TypeError: 'tuple' object cannot be interpreted as an integer